### ISSUE TITLE
Roadmap: Project Build

### ISSUE THREAD

**Issue by 7wf** [statikksh/api#2]
###### Roadmap for projects builds.

- [x] Setup AMQP/RabbitMQ connection. (*Statikk uses RabbitMQ to share messages between the Project Build worker and the API server*)
- [x] Create a new model for project builds.
- [x] Allow authenticated users to manually run builds of their own projects.
- [x] Real-time logging of project builds.

**Comment by 7wf** [comment]
Real-time logging feature requires the build server to send build logs through a RabbitMQ queue.
